[project]
name = "doc-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "azure-functions",
    "azure-ai-documentintelligence",
    "azure-core",
    "sqlalchemy",
    "psycopg2-binary",
    "openai"
]
